// <auto-generated />
using System;
using CarRent.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRent.DAL.Migrations
{
    [DbContext(typeof(CarRentDbContext))]
    partial class CarRentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("CarRent.Model.Entities.Addon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "GPS",
                            PricePerDay = 4m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Djecja sjedalica",
                            PricePerDay = 6m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Premium osiguranje",
                            PricePerDay = 12m
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JMBG")
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CarRent.Model.Entities.BranchOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("LocationType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BranchOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ilica 1",
                            LocationType = 2,
                            Name = "Zagreb Centar",
                            Phone = "+385111111"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Airport Rd 10",
                            LocationType = 1,
                            Name = "Zagreb Airport",
                            Phone = "+385222222"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Riva 5",
                            LocationType = 0,
                            Name = "Split Riva",
                            Phone = "+385333333"
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1994, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicenseNumber = "HR001",
                            Email = "marko@example.com",
                            FirstName = "Marko",
                            LastName = "Horvat",
                            Phone = "+38591000111"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1998, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicenseNumber = "HR002",
                            Email = "iva@example.com",
                            FirstName = "Iva",
                            LastName = "Peric",
                            Phone = "+38591000222"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1989, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicenseNumber = "HR003",
                            Email = "luka@example.com",
                            FirstName = "Luka",
                            LastName = "Maric",
                            Phone = "+38591000333"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(2000, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DriverLicenseNumber = "HR004",
                            Email = "ana@example.com",
                            FirstName = "Ana",
                            LastName = "Kovacic",
                            Phone = "+38591000444"
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchOfficeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchOfficeId = 1,
                            FirstName = "Petra",
                            HiredAt = new DateTime(2022, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitle = "Voditelj poslovnice",
                            LastName = "Barišić"
                        },
                        new
                        {
                            Id = 2,
                            BranchOfficeId = 2,
                            FirstName = "Ivan",
                            HiredAt = new DateTime(2024, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitle = "Dispečer voznog parka",
                            LastName = "Matić"
                        },
                        new
                        {
                            Id = 3,
                            BranchOfficeId = 3,
                            FirstName = "Lucija",
                            HiredAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            JobTitle = "Podrška korisnicima",
                            LastName = "Rajić"
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.FleetNotificationOutbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DedupKey")
                        .IsUnique();

                    b.ToTable("FleetNotificationOutbox");
                });

            modelBuilder.Entity("CarRent.Model.Entities.FleetPushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("FleetPushSubscriptions");
                });

            modelBuilder.Entity("CarRent.Model.Entities.Partner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Partners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Hotel Aurora",
                            ContactPerson = "Mario Lovrić",
                            Email = "mario@aurora.hr",
                            Phone = "+38599888111"
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Travel Hub Adriatic",
                            ContactPerson = "Nina Grgić",
                            Email = "nina@travelhub.hr",
                            Phone = "+38599888222"
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Airport Shuttle Plus",
                            ContactPerson = "Filip Kranjčec",
                            Email = "filip@shuttleplus.hr",
                            Phone = "+38599888333"
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DropoffLocation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MileageUpdateSuggested")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PickupLocation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 165m,
                            CreatedAt = new DateTime(2026, 4, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            DropoffLocation = 1,
                            EndDate = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = 2,
                            MileageUpdateSuggested = false,
                            StartDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 316m,
                            CreatedAt = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            DropoffLocation = 0,
                            EndDate = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = 1,
                            MileageUpdateSuggested = false,
                            StartDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 30m,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 3,
                            DropoffLocation = 0,
                            EndDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = 0,
                            MileageUpdateSuggested = false,
                            StartDate = new DateTime(2026, 4, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 200m,
                            CreatedAt = new DateTime(2026, 4, 15, 4, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 4,
                            DropoffLocation = 2,
                            EndDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = 2,
                            MileageUpdateSuggested = false,
                            StartDate = new DateTime(2026, 4, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 256m,
                            CreatedAt = new DateTime(2026, 4, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 1,
                            DropoffLocation = 3,
                            EndDate = new DateTime(2026, 4, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = 0,
                            MileageUpdateSuggested = false,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            VehicleId = 5
                        },
                        new
                        {
                            Id = 6,
                            BasePrice = 36m,
                            CreatedAt = new DateTime(2026, 4, 15, 16, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = 2,
                            DropoffLocation = 2,
                            EndDate = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            PickupLocation = 1,
                            MileageUpdateSuggested = false,
                            StartDate = new DateTime(2026, 4, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VehicleId = 6
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.ReservationAddon", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddonName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceAtReservation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReservationId", "AddonId");

                    b.HasIndex("AddonId");

                    b.ToTable("ReservationAddons");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            AddonId = 1,
                            AddonName = "GPS",
                            PriceAtReservation = 4m,
                            Quantity = 3
                        },
                        new
                        {
                            ReservationId = 2,
                            AddonId = 3,
                            AddonName = "Premium osiguranje",
                            PriceAtReservation = 12m,
                            Quantity = 4
                        },
                        new
                        {
                            ReservationId = 3,
                            AddonId = 2,
                            AddonName = "Djecja sjedalica",
                            PriceAtReservation = 6m,
                            Quantity = 1
                        },
                        new
                        {
                            ReservationId = 4,
                            AddonId = 1,
                            AddonName = "GPS",
                            PriceAtReservation = 4m,
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("MileageAtService")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRecommendedServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 240m,
                            Description = "Mali servis",
                            MileageAtService = 73000,
                            NextRecommendedServiceDate = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceDate = new DateTime(2026, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 300m,
                            Description = "Zamjena guma",
                            MileageAtService = 90000,
                            NextRecommendedServiceDate = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceDate = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Cost = 410m,
                            Description = "Kocnice",
                            MileageAtService = 125500,
                            NextRecommendedServiceDate = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            Cost = 90m,
                            Description = "Pregled skutera",
                            MileageAtService = 8100,
                            NextRecommendedServiceDate = new DateTime(2026, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceDate = new DateTime(2026, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            VehicleId = 4
                        },
                        new
                        {
                            Id = 5,
                            Cost = 180m,
                            Description = "Lanac i ulje",
                            MileageAtService = 14500,
                            NextRecommendedServiceDate = new DateTime(2026, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            ServiceDate = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            VehicleId = 5
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BlockedByService")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActiveBeforeServiceBlock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MileageKm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MainImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("RegistrationDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BranchOfficeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchOfficeId = 1,
                            BlockedByService = false,
                            Brand = "Skoda",
                            DailyPrice = 55m,
                            IsActive = true,
                            IsActiveBeforeServiceBlock = true,
                            MileageKm = 75500,
                            Model = "Octavia",
                            RegistrationNumber = "ZG-100-AA",
                            Type = 0,
                            Year = 2021
                        },
                        new
                        {
                            Id = 2,
                            BranchOfficeId = 1,
                            BlockedByService = false,
                            Brand = "Volkswagen",
                            DailyPrice = 50m,
                            IsActive = true,
                            IsActiveBeforeServiceBlock = true,
                            MileageKm = 91400,
                            Model = "Golf",
                            RegistrationNumber = "ZG-200-BB",
                            Type = 0,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            BranchOfficeId = 2,
                            BlockedByService = false,
                            Brand = "Renault",
                            DailyPrice = 79m,
                            IsActive = true,
                            IsActiveBeforeServiceBlock = true,
                            MileageKm = 126000,
                            Model = "Trafic",
                            RegistrationNumber = "ZG-300-CC",
                            Type = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 4,
                            BranchOfficeId = 3,
                            BlockedByService = false,
                            Brand = "Piaggio",
                            DailyPrice = 30m,
                            IsActive = true,
                            IsActiveBeforeServiceBlock = true,
                            MileageKm = 8300,
                            Model = "Liberty",
                            RegistrationNumber = "ST-400-DD",
                            Type = 2,
                            Year = 2023
                        },
                        new
                        {
                            Id = 5,
                            BranchOfficeId = 3,
                            BlockedByService = false,
                            Brand = "Yamaha",
                            DailyPrice = 64m,
                            IsActive = true,
                            IsActiveBeforeServiceBlock = true,
                            MileageKm = 14500,
                            Model = "MT-07",
                            RegistrationNumber = "ST-500-EE",
                            Type = 3,
                            Year = 2022
                        },
                        new
                        {
                            Id = 6,
                            BranchOfficeId = 2,
                            BlockedByService = false,
                            Brand = "Cube",
                            DailyPrice = 18m,
                            IsActive = true,
                            IsActiveBeforeServiceBlock = true,
                            MileageKm = 1900,
                            Model = "Touring",
                            RegistrationNumber = "ZG-600-FF",
                            Type = 4,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CarRent.Model.Entities.VehicleAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleAttachments");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CarRent.Model.Entities.Employee", b =>
                {
                    b.HasOne("CarRent.Model.Entities.BranchOffice", "BranchOffice")
                        .WithMany("Employees")
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchOffice");
                });

            modelBuilder.Entity("CarRent.Model.Entities.Reservation", b =>
                {
                    b.HasOne("CarRent.Model.Entities.Customer", "Customer")
                        .WithMany("Reservations")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRent.Model.Entities.Vehicle", "Vehicle")
                        .WithMany("Reservations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRent.Model.Entities.ReservationAddon", b =>
                {
                    b.HasOne("CarRent.Model.Entities.Addon", "Addon")
                        .WithMany("ReservationAddons")
                        .HasForeignKey("AddonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRent.Model.Entities.Reservation", "Reservation")
                        .WithMany("Addons")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addon");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("CarRent.Model.Entities.ServiceRecord", b =>
                {
                    b.HasOne("CarRent.Model.Entities.Vehicle", "Vehicle")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRent.Model.Entities.Vehicle", b =>
                {
                    b.HasOne("CarRent.Model.Entities.BranchOffice", "BranchOffice")
                        .WithMany("Vehicles")
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchOffice");
                });

            modelBuilder.Entity("CarRent.Model.Entities.VehicleAttachment", b =>
                {
                    b.HasOne("CarRent.Model.Entities.Vehicle", "Vehicle")
                        .WithMany("Attachments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CarRent.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CarRent.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRent.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CarRent.Model.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRent.Model.Entities.Addon", b =>
                {
                    b.Navigation("ReservationAddons");
                });

            modelBuilder.Entity("CarRent.Model.Entities.BranchOffice", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarRent.Model.Entities.Customer", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarRent.Model.Entities.Reservation", b =>
                {
                    b.Navigation("Addons");
                });

            modelBuilder.Entity("CarRent.Model.Entities.Vehicle", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Reservations");

                    b.Navigation("ServiceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
